# This is a basic workflow to help you get started with Actions

name: CI_metrics_history

# https://docs.github.com/en/actions/how-tos/write-workflows/choose-when-workflows-run/trigger-a-workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # https://github.com/actions/runner-images
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          # fetch all history for all branches and tags
          fetch-depth: 0

      # Runs a set of commands using the runners shell
      - name: Generate site sources
        run: |
          cd $GITHUB_WORKSPACE
          pip install -r requirements.txt
          cd public_site_sources
          bash get_metric_history.sh
          python image_generator.py
          cd ..
          echo "History pictures were generated"

      - name: Upload site static files
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: public_site_sources/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
